### ISSUE TITLE
Box Maker dont open dialog in SketchUp 2016

### ISSUE THREAD

**Issue by MildaGenius** [subhero24/box-maker#3]
Hello,
I installed Box Maker to SketchUp 2016. I can see Box item in Draw menu, but after selection, nothing happend.

Its Box Maker only for Pro version?

Thanks

M

**Comment by subhero24** [comment]
I don't think you need the Pro version. I only have sketchup 2018 so can not test it in sketchup 2016. But it works under 2018. Can you check if the ruby console reports any errors?

**Comment by MildaGenius** [comment]
Here is error from Ruby console:
`Error: #<NameError: uninitialized constant UI::HtmlDialog>
C:/Users/Milan/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/box-maker/main.rb:7:in make_box'
C:/Users/Milan/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/box-maker/main.rb:52:in block in <module:BoxMaker>'
SketchUp:1:in call`

**Comment by subhero24** [comment]
I see. The HtmlDialog i'm using is only supported from sketchup 2017 and higher i'm afraid ...

**Comment by MildaGenius** [comment]
Yes, I found it in documentation too :).

I can confirm, that in SketchUp 2017 works MakerBox as expect.

So probably is time to move to 2017 version.

Thanks for help and plugin.

M

**Comment by subhero24** [comment]
I think this should be a quick fix. I have updated the plugin. Can you check if it works now? Thanks

**Comment by MildaGenius** [comment]
Tested new version, but the same problem:

`Error: #<NameError: uninitialized constant UI::HtmlDialog>
C:/Users/Milan/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/box-maker/main.rb:7:in make_box
C:/Users/Milan/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/box-maker/main.rb:52:in block in <module:BoxMaker>
SketchUp:1:in call`

New version has the same version number 0.0.3 as previous. But I checked that the new installed version has your change.

`dialogtype = UI::HtmlDialog || UI::WebDialog`

**Comment by subhero24** [comment]
I gave it another try (this time with version bump). If you could test it again, i would be grateful.

**Comment by MildaGenius** [comment]
Settings dialog is visible now, but after pressed "Make a box" button, nothing happend.

Version still presents as 0.0.3.

**Comment by subhero24** [comment]
I found a trial version of sketchup 2016 to install and test it. It is working now. Please upgrade the plugin and make sure version is at 0.0.4 (if not try reinstalling the plugin)

**Comment by tavdog** [comment]
I'm trying to get this to work in Sketchup 2017 and the window pops up but is blank. Nothing in the ruby console.

**Comment by subhero24** [comment]
The problem with Sketchup 2017 should be fixed now. Give it a try and let me know if it works.

**Comment by tavdog** [comment]
Yes it works. Thanks so much !
